### PR TITLE
IPD 27 - EOF luxadm

### PR DESCRIPTION
**Pull request by gdamore**

### CODE REVIEW

**Comment by ptribble** [comment]
luxadm saw significant use on x86 also, and while I am unable to remember the precise details from 7 years ago, we were still using luxadm on x86 because not every piece of functionality had been pushed to the newer utilities like fcinfo. That's not to say it can't be removed, but the statement it being unlikely to have been used on x86 outside of Sun is incorrect.

**Comment by jclulow** [comment]
If you could dig up the details on what it gets used for that would be super helpful.  It feels like some combination of `fcinfo`, `fcadm`, `cfgadm`, and perhaps `mpathadm`, _should_ be able to cover all the bases, but if there's missing coverage we should plug those holes.

**Comment by tsoome** [comment]
> If you could dig up the details on what it gets used for that would be super helpful. It feels like some combination of `fcinfo`, `fcadm`, `cfgadm`, and perhaps `mpathadm`, _should_ be able to cover all the bases, but if there's missing coverage we should plug those holes.

I guess, it should be luxadm -e force_lip.

**Comment by gdamore** [comment]
fcadm force-lip should do it

**Comment by gdamore** [comment]
> luxadm saw significant use on x86 also, and while I am unable to remember the precise details from 7 years ago, we were still using luxadm on x86 because not every piece of functionality had been pushed to the newer utilities like fcinfo. That's not to say it can't be removed, but the statement it being unlikely to have been used on x86 outside of Sun is incorrect.

This is good information, and not something I was previously aware of -- I really thought this was only used with legacy FC-AL installations (socal/sf stack on SPARC)... I didn't even know it would work with other topologies or newer hardware.

**Comment by gdamore** [comment]
I'm going to close this for now; it appears that luxadm is basically similar to fcadm and fcinfo, and it's removal won't really achieve very much useful.

**Pull request closed without merging**
