### PR TITLE
IPD 26 - Sunset CardBus and PC Card

### PR DESCRIPTION
**Pull request by gdamore**

### CODE REVIEW

**Comment by jclulow** [comment]
Probably worth mentioning prior mailing list threads about this stuff; e.g., at least:

- [obsolete legacy PCMCIA (FEB 2012)](https://illumos.topicbox.com/groups/developer/Te2c90b02ebe5b0aa-M526606b14e4160e4e3231875/obsolete-legacy-pcmcia)
- [Proposal: EOF pcmcia bits (SEP 2013)](https://illumos.topicbox.com/groups/developer/T3be2124e9f17aa04-Maa11cbaf947ea116077801cf/proposal-eof-pcmcia-bits)
- [webrev: removal of cardbus (AUG 2014)](https://illumos.topicbox.com/groups/developer/T5edf352487b49a3b-Mcf2cecc58cdd912926f8bd63/webrev-removal-of-cardbus)

**Comment by jclulow** [comment]
Also, I guess, related open tickets; e.g.,

* [680 pm_create_components ought to be cleaned up](https://www.illumos.org/issues/680)
* [2398 pcs driver should be removed](https://www.illumos.org/issues/2398)
* [5075 EOF cardbus & pcmcia](https://www.illumos.org/issues/5075)
* [8510 pcmcia: typo in pcmcia_prop_op](https://www.illumos.org/issues/8510)

**Comment by gdamore** [comment]
thanks for the feedback, I've updated.

**Comment by jclulow** [comment]
If you make it a `draft` rather than a `predraft`, we can squash-and-merge it, and then you can punt it out to the developer list.  I don't anticipate anybody will object, and I'm happy to sponsor it on Monday or whatever?

**Comment by gdamore** [comment]
should I squash/rebase/push ?

**Comment by jclulow** [comment]
I am generally sceptical of the green button but ... it seems to have done the right thing! :D

**Pull request merged**
